// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbYB4mtXgoeB02C1iNiTNywtD_bS-Rc3Q',
    appId: '1:977226399867:web:1686f65b7f15b11eee22de',
    messagingSenderId: '977226399867',
    projectId: 'comp589-c1db0',
    authDomain: 'comp589-c1db0.firebaseapp.com',
    storageBucket: 'comp589-c1db0.appspot.com',
    measurementId: 'G-RX6PSGLG5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA5AkQS9de1NOAZ7R8IMimylDc5GTr3Fs',
    appId: '1:977226399867:android:1464d6739312f78eee22de',
    messagingSenderId: '977226399867',
    projectId: 'comp589-c1db0',
    storageBucket: 'comp589-c1db0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzUWIiq70MlCX8d4EF87gZmqu0e0SLPgc',
    appId: '1:977226399867:ios:c7eaa91e93f19720ee22de',
    messagingSenderId: '977226399867',
    projectId: 'comp589-c1db0',
    storageBucket: 'comp589-c1db0.appspot.com',
    iosClientId: '977226399867-b41su22pnl6ihr5seu58u5rmu1g2kv7j.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzUWIiq70MlCX8d4EF87gZmqu0e0SLPgc',
    appId: '1:977226399867:ios:c7eaa91e93f19720ee22de',
    messagingSenderId: '977226399867',
    projectId: 'comp589-c1db0',
    storageBucket: 'comp589-c1db0.appspot.com',
    iosClientId: '977226399867-b41su22pnl6ihr5seu58u5rmu1g2kv7j.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
